<?php
        header('Content-Type: application/json');

echo json_encode(array(
    "Aberdeen","Abergavenny","Abingdon","Accrington","Acle","Albrighton","Alcester","Alconbury","Aldeburgh",
    "Alderbury","Alfreton","Alsager","Amersham","Amesbury","Ammanford","Ampthill","Andover","Antrim",
    "Appledore","Arbroath","Armadale","Arundel","Ascot","Ashbourne","Ashburton","Ashby-de-la-Zouch","Ashford",
    "Ashington","Ashton","Atherstone","Attleborough","Aylesbury","Aylsham","Bacup","Ballyclare","Banchory",
    "Bangor","Bar Hill","Barnard Castle","Barnoldswick","Barnsley","Barnstaple","Barrow upon Humber","Barry",
    "Barton-upon-Humber","Basildon","Basingstoke","Bath","Bathgate","Battle","Bawtry","Beaconsfield",
    "Beaminster","Beccles","Bedford","Bedlington","Beith","Belfast","Belper","Bere Regis","Berkhamsted",
    "Beverley","Bexhill","Bicester","Biddulph","Bideford","Biggleswade","Bingham","Birkenhead Urban Area",
    "Birmingham-Wolverhampton","Bishop Auckland","Bishop's Cleeve","Bishop's Stortford","Bishop's Waltham",
    "Bishopsteignton","Blackburn","Blackpool","Blaenavon","Blandford Forum","Blofield","Blyth","Bognor Regis",
    "Bognor Regis","Bolsover","Bonnyrigg","Bottesford","Bourne","Bournemouth-Poole","Bovey Tracey","Brackley",
    "Bracknell","Bradford","Braintree","Bransgore","Branston","Braunton","Brentwood","Bridgend","Bridgnorth",
    "Bridgwater","Bridport","Brightlingsea","Brighton","Bristol","Bromham","Brough","Broxburn","Brundall",
    "Bruton","Brynmawr","Buckfastleigh","Buckingham","Budleigh Salterton","Bungay","Burford","Burgess Hill",
    "Burnham-on-Sea","Burnley","Burry Port","Burton upon Trent","Burwell","Buxton","Caerphilly","Caistor",
    "Callington","Calne","Cambourne","Cambridge","Cannock","Canterbury","Capel St. Mary","Cardiff","Carluke",
    "Carnoustie","Carrickfergus","Carryduff","Carterton","Castle Cary","Castle Donington","Castleford",
    "Catterick Garrison","Chapel-en-le-Frith","Chapeltown","Chard","Charlbury","Charminster","Cheadle",
    "Cheddar","Chelmsford","Cheltenham","Chepstow","Cherry Willingham","Chesham","Cheshunt","Chester",
    "Chester-le-Street","Chesterfield","Chichester","Chippenham","Chipping Norton","Chorley","Chudleigh",
    "Church Stretton","Cinderford","Cirencester","Clackmannanshire","Clacton-on-Sea","Clay Cross","Cleethorpes",
    "Clevedon","Clitheroe","Clowne","Coalville","Coggeshall","Colchester","Collingham","Comber","Congleton",
    "Conisbrough","Consett","Corbridge","Corby","Corsham","Cottenham","Coupar Angus","Coventry","Cowbridge",
    "Cowdenbeath","Craigavon","Cramlington","Crankbrook","Crawley","Crediton","Crewe","Crewkerne","Cricklade",
    "Crowland","Cullompton","Cumbernauld","Cwmbran","Cynon Valley","Dalgety Bay","Dalkeith","Darlington",
    "Daventry","Dawlish","Deal","Dearne Valley","Debenham","Derby","Dereham","Devizes","Dewsbury","Didcot",
    "Dinnington","Doncaster","Dorchester","Dorking","Dover","Downton","Dromore","Dronfield","Dumbarton","Dunbar",
    "Dundee","Dunfermline","Durham","Durrington","Dursley","Dyce","Earby","Earl Shilton","Easingwold",
    "East Grinstead","East Kilbride","Eastbourne","Eastwood","Ebbw Vale","Ebbw Vale","Eckington","Edinburgh",
    "Ellon","Ely","Exeter","Exminster","Exmouth","Falkirk","Fareham","Faringdon","Farnborough/Aldershot",
    "Faversham","Felixstowe","Fenstanton","Ferndown","Fleetwood","Flitwick","Folkestone","Fordingbridge",
    "Forfar","Framlingham","Frinton and Walton","Frome","Gainsborough","Garstang","Gillingham","Glasgow",
    "Glastonbury","Glenrothes","Glossop","Gloucester","Godmanchester","Goole","Gorebridge","Gosport",
    "Grantham","Gravesend","Grays","Great Ayton","Great Torrington","Great Yarmouth","Greater London Urban Area",
    "Greater Manchester Urban Area","Greenock","Grimsby","Guildford","Guisborough","Haddington","Hadleigh",
    "Hailsham","Halifax","Halstead","Hamilton","Harlow","Harpenden","Harrogate","Hartlepool","Harwich","Haslingden",
    "Hastings","Hatfield","Hatfield","Havant","Haverhill","Haywards Heath","Heanor","Hedon","Helensburgh",
    "Hemel Hempstead","Herne Bay","Hertford","Hethersett","Hexham","High Wycombe","Highworth","Hinckley",
    "Hitchin","Hoddesdon","Holmes Chapel","Holmfirth","Honiton","Horncastle","Hornsea","Horsford","Horsham",
    "Houghton-le-Spring","Howden","Huddersfield","Hull","Hungerford","Hungerford","Huntingdon","Hythe","Hythe",
    "Ilchester","Ilfracombe","Ilkeston","Ilkley","Ilminster","Immingham","Inchture","Inverurie","Ipswich",
    "Irthlingborough","Ivybridge","Keelby","Kegworth","Keighley","Kenilworth","Kessingland","Kettering",
    "Keyingham","Kilbirnie","Killamarsh","Kilmarnock","Kingsclere","Kingskerswell","Kintore","Kirkcaldy",
    "Kirkham","Kirkintilloch","Kirriemuir","Knaresborough","Knutsford","Laceby","Lanark","Langport","Larkhall",
    "Larne","Leamington","Lechlade","Leeds","Leek","Leicester","Leighton Buzzard","Leiston","Leonards and St Ives",
    "Lesmahagow","Letchworth","Levan","Levenmouth","Lewes","Leyland","Lichfield","Lincoln","Linlithgow","Linton",
    "Liskeard","Littlehampton","Liverpool Urban Area","Livingston","Llanelli","Llantwit Major","Loanhead",
    "Loggerheads","Long Stratton","Longridge","Longstanton","Loughborough","Louth","Lowestoft","Ludgershall",
    "Luton/Dunstable","Lutterworth","Lydd","Lymington","Lyndhurst","Lytchett Matravers","Macclesfield","Maesteg",
    "Magor","Maidenhead","Maidstone","Malmesbury","Maltby","Malton","Manningtree","Mansfield","March",
    "Margate-Ramsgate-Broadstairs","Market Deeping","Market Drayton","Market Harborough","Market Rasen",
    "Market Weighton","Marlborough","Marple","Mattishall","Medway","Melksham","Melton Mowbray","Mersea Island",
    "Merthyr Tydfil","Metheringham","Mexborough","Middlesbrough","Middlewich","Midsomer Norton","Milford on Sea",
    "Milton Keynes","Mitcheldean","Moira","Monmouth","Moretonhampstead","Morpeth","Motherwell","Much Wenlock",
    "Mulbarton","Musselburgh","Nailsea","Nantwich","Navenby","Neath-Port Talbot","Needham Market","Nettleham",
    "New Alresford","New Mills","New Romney","Newark","Newbury","Newcastle","Newent","Newhaven","Newmarket",
    "Newport","Newport","Newport-on-Tay","Newton Abbott","Newton Aycliffe","Newtonhill","Newtownards",
    "North Ferriby","Northallerton","Northam","Northampton","Northwich","Norton","Norwich","Nottingham",
    "Nuneaton","Oakham","Oldmeldrum","Ormskirk","Otley","Ottery St Mary","Oundle","Oxford","Papworth Everard",
    "Peacehaven","Pencoed","Penicuik","Penistone","Peterborough","Peterculter","Peterlee","Petersfield",
    "Plymouth","Pocklington","Pontarddulais","Pontefract","Ponteland","Pontesbury","Pontycymer","Pontypool",
    "Pontypridd","Porthcawl","Portishead","Portlethen","Portsmouth","Preston","Prestonpans","Prudhoe","Pyle",
    "Queensferry","Radcliffe-on-Trent","Radstock","Ramsey","Randalstown","Rawtenstall","Reading","Redhill",
    "Reigate","Rhondda Valley","Rhymney","Richmond","Ringwood","Ripley","Robertsbridge","Romsey","Rotherham",
    "Royal Wootton Bassett","Royston","Rugby","Rugeley","Runcorn","Rushden","Ruskington","Rye","Saffron Walden",
    "Salisbury","Saltash","Sandbach","Sandwich","Sandy","Sawston","Sawtry","Saxilby","Saxmundham","Seaford",
    "Seaham","Sedgefield","Selby","Selsey","Sevenoaks","Shaftesbury","Sheerness","Sheffield","Shefford",
    "Shepshed","Shepton Mallet","Sherborne","Shifnal","Shirebrook","Shrewsbury","Sidmouth","Sittingbourne",
    "Skellingthorpe","Skelmersdale","Skipton","Sleaford","Slough","Soham","Somerton","South Brent","South Cave",
    "South Molton","Southam","Southampton","Southend","Southport","Southwell","Spalding","Spennymoor","Spixworth",
    "St Ives","St Neots","St. Albans","Stalbridge","Stamford","Stamford Bridge","Stanley","Stapleford",
    "Stevenage","Steyning","Stilton","Stirling","Stocksbridge","Stoke-on-Trent","Stokesley","Stone","Stonehaven",
    "Stowmarket","Strathaven","Street","Stroud","Sudbury","Sunderland","Swanland","Swansea","Swindon","Tadcaster",
    "Tamworth","Taunton","Tavistock","Teignmouth","Telford","Tenterden","Tewkesbury","Thame","Thornbury","Thorne",
    "Thorngumbald","Thrapston","Tickhill","Tidworth","Tiptree","Tiverton","Tonbridge","Tonyrefail","Topsham",
    "Torbay","Torpoint","Totnes","Towcester","Tranent","Tredegar","Treharris","Trowbridge","Tunbridge Wells",
    "Uckfield","Uppingham","Usk","Uttoxeter","Verwood","Wakefield","Wallingford","Wantage","Ware","Wareham",
    "Warminster","Warrington","Warsop","Warwick","Washingborough","Waterlooville","Watlington","Wellingborough",
    "Wellington","Wells","Welton","Welwyn Garden City","Wem","West Moors","Westbury","Westhill",
    "Weston-super-Mare","Wetherby","Weymouth","Whitburn","Whitchurch","Whitstable","Whittlesey","Wickham Market",
    "Widnes","Wigan","Wimborne Minster","Wincanton","Winchcombe","Winchelsea","Winchester","Windsor","Winsford",
    "Winslow","Wishaw","Withernsea","Witney","Wittering","Wiveliscombe","Woking","Woodhall Spa","Woodstock",
    "Worksop","Worthing","Wotton-under-Edge","Wragby","Wroxham","Wymondham","Yate","Yaxley","Yeovil","York",
    "Ystrad Mynach","Ystradgynlais"));